version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.20
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    mem_limit: 2g
    cpus: 1.5

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.20
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - NODE_OPTIONS=--max-old-space-size=512
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    mem_limit: 1g
    cpus: 1

  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    command: ["-i", "YOUR_INTERFACE_HERE"]
    volumes:
      - ./suricata/logs:/var/log/suricata
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    mem_limit: 512m
    cpus: 1

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.20
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./suricata/logs:/var/log/suricata:ro
    depends_on:
      - elasticsearch
    mem_limit: 512m
    cpus: 0.5

volumes:
  esdata:
